### ISSUE TITLE
The requested URL was not found on this server. 

### ISSUE THREAD

**Issue by sileclercq** [modess/git-pretty-stats#20]
HEre is the url of my server : http://par-svr-app02:8084/git-pretty-stats/public/

Here is the list of the repository which is displayed on this page : 
D:\repo\GitBlit @ master
37 commits
D:\repo\Vss2Git @ master
22 commits

When I click on the first one, I get the following page and error : 
http://par-svr-app02:8084/git-pretty-stats/public/repository/D%3A%5Crepo%5CGitBlit
--
Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

par-svr-app02
02/13/14 18:35:35
Apache/2.2.21 (Win32) DAV/2 mod_ssl/2.2.21 OpenSSL/1.0.0e PHP/5.3.8 mod_perl/2.0.4 Perl/v5.10.1
--

What do I need to do to fix this  ? 
Thanks for the help

**Comment by modess** [comment]
I know this is a very old issue, but I believe now I have added Windows support. Please see https://github.com/modess/git-pretty-stats/issues/31#issuecomment-87271721
