### ISSUE TITLE
Remove requests to fonts.googleapis.com

### ISSUE THREAD

**Issue by tetraf** [modess/git-pretty-stats#33]
For privacy concerns it may be good to remove references to fonts.googleapis.com and to distribute (or not) fonts locally.

→ https://github.com/modess/git-pretty-stats/blob/c8defa546dfe77910189b078c241e42af3bc9f52/app/views/index.php#L12

**Comment by modess** [comment]
This have never crossed my mind. I can easily just make it distribute locally instead.

**Comment by tetraf** [comment]
Thanks.

**Comment by modess** [comment]
I released a patch version (https://github.com/modess/git-pretty-stats/commit/79e296272b75a97a1d2cd0d4fa24ab3651fc836a) now that serves the fonts locally instead from big brother :)
